name: Build Thesis

on:
  push:
  pull_request:
  schedule:
    - cron: '0 16 * * 1'  # Build every monday, 16:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install texlive
      run: |
        pip install https://github.com/maxnoe/texlive-batch-installation/archive/refs/tags/v0.3.0.tar.gz
        install_texlive -p $HOME/texlive -t 2021 --collections="-a" --package-file tex-packages.txt --update
        echo "$HOME/texlive/2021/bin/x86_64-linux" >> $GITHUB_PATH
    
    - name: Download the fonts
      run: for i in LibertinusMono-Regular.otf, LibertinusSerifInitials-Regular.otf, LibertinusSerifDisplay-Regular.otf, LibertinusSerif-SemiboldItalic.otf, LibertinusSerif-Semibold.otf, LibertinusMath-Regular.otf, LibertinusSerif-Regular.otf, LibertinusSans-Bold.otf, LibertinusSans-Italic.otf, LibertinusSans-Regular.otf, LibertinusSerif-Bold.otf, LibertinusSerif-BoldItalic.otf, LibertinusSerif-Italic.otf; do curl -OL mirrors.ctan.org/fonts/libertinus-fonts/otf/$i > fonts/$i; done
    
    - name: Copy the fonts # In newer version of fontconfig, it reads $HOME/.local/share/fonts/ but not $HOME/.fonts
      run: mkdir -p ~/.local/share/fonts && cp -r fonts/* ~/.local/share/fonts/
   
    - name: Build font information caches
      run: fc-cache -rv
    
    - name: Build document
      run: |
        latexmk
